{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .Release.Name }}-cnpg
spec:
  externalSecretName: {{ .Values.cnpg.copySecretName }}

  refreshTime: "1h"

  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: {{ .Values.eso.clusterSecretStoreName }}
      kind: ClusterSecretStore
    target:
      name: {{ .Values.cnpg.copySecretName }}
      creationPolicy: Owner
    data:
      - secretKey: host
        remoteRef:
          key: {{ .Values.cnpg.secretName }}
          property: host
      - secretKey: port
        remoteRef:
          key: {{ .Values.cnpg.secretName }}
          property: port
      - secretKey: dbname
        remoteRef:
          key: {{ .Values.cnpg.secretName }}
          property: dbname
      - secretKey: username
        remoteRef:
          key: {{ .Values.cnpg.secretName }}
          property: username
      - secretKey: password
        remoteRef:
          key: {{ .Values.cnpg.secretName }}
          property: password
      - secretKey: pgpass
        remoteRef:
          key: {{ .Values.cnpg.secretName }}
          property: pgpass

  namespaces:
    - {{ .Release.Namespace }}
{{- end }}
